from .bfl_api import (
    FluxPro,
    FluxDev,
    FluxPro11,
    FluxCanny,
    FluxDepth,
    FluxUltra11,
    FluxProFill,
    FluxProFinetune,
    FluxProCannyFinetune,
    FluxProDepthFinetune,
    FluxProFillFinetune,
    FluxUltra11Finetune,
    Flux2Pro,
    Flux2ProPreview,
    Flux2Max,
    Flux2Flex,
)

NODE_CLASS_MAPPINGS = {
    "FLUX 1.0 [pro]": FluxPro,
    "FLUX 1.0 [dev]": FluxDev,
    "FLUX 1.1 [pro]": FluxPro11,
    "FLUX 1.1 [ultra]": FluxUltra11,
    "FLUX 1.0 [depth]": FluxDepth,
    "FLUX 1.0 [canny]": FluxCanny,
    "FLUX 1.0 [fill]": FluxProFill,
    "FLUX 1.0 [pro] Finetuned": FluxProFinetune,
    "FLUX 1.0 [canny] Finetuned": FluxProCannyFinetune,
    "FLUX 1.0 [depth] Finetuned": FluxProDepthFinetune,
    "FLUX 1.0 [fill] Finetuned": FluxProFillFinetune,
    "FLUX 1.1 [ultra] Finetuned": FluxUltra11Finetune,

    "FLUX.2 [pro]": Flux2Pro,
    "FLUX.2 [pro] Preview": Flux2ProPreview,
    "FLUX.2 [max]": Flux2Max,
    "FLUX.2 [flex]": Flux2Flex,
}
